from django.contrib.auth.models import AbstractUser, Group, Permission
from django.db import models

class CustomUser(AbstractUser):
    email = models.EmailField(unique=True)
    branch = models.CharField(max_length=255)
    desgination = models.CharField(max_length=255)
    date_of_birth = models.DateField()
    father_name = models.CharField(max_length=255)
    grand_father_name = models.CharField(max_length=255, blank=True, null=True)
    mother_name = models.CharField(max_length=255)
    perm_state = models.CharField(max_length=255)
    perm_district = models.CharField(max_length=255)
    perm_municipality = models.CharField(max_length=255)
    perm_ward_no = models.CharField(max_length=255)
    temp_state = models.CharField(max_length=255)
    temp_district = models.CharField(max_length=255)
    temp_municipality = models.CharField(max_length=255)
    temp_ward_no = models.CharField(max_length=255)
    citizenship_id = models.CharField(max_length=255, unique=True)
    citizenship_date_of_issue = models.DateField()
    citizenship_district = models.CharField(max_length=255)
    citizenship_front_image = models.ImageField(upload_to='citizenship/')
    citizenship_back_image = models.ImageField(upload_to='citizenship/')
    home_number = models.CharField(max_length=255)
    phone_number = models.CharField(max_length=255)
    mobile_number = models.CharField(max_length=255)
    office = models.CharField(max_length=255)
    date_joined = models.DateTimeField()
    recess_date = models.DateTimeField()
    is_active = models.BooleanField(default=True)
    is_staff = models.BooleanField(default=False)
    is_superuser = models.BooleanField(default=False)

    groups = models.ManyToManyField(Group, related_name="customuser_groups", blank=True)
    user_permissions = models.ManyToManyField(Permission, related_name="customuser_permissions", blank=True)
